name: Build and deploy Node.js app to Azure Web App - myapp-monica

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: npm install
        run: npm install

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5AD527ADF613450E99E71298F439063D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D38FBEDFA2CC46EF9161A8931DAE4FA3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_747A8C78F2A64C6EB3F95F303007EA9A }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'myapp-monica'
          slot-name: 'Production'
          package: .